### ISSUE TITLE
Dashboard stops working

### ISSUE THREAD

**Issue by EvHackerLol** [felixhahnweilheim/humhub-flex-theme#20] opened 2023-03-29 06:51 UTC
Hello, 
After uploading and activating this theme, dashboard stops working. :/

![image](https://user-images.githubusercontent.com/90171014/228450049-260a7139-bb68-40e3-996c-1be1f5988d71.png)

**Comment by felixhahnweilheim** [comment] 2023-03-30 07:28
Hi, thank you for the issue.
"Under development" means that such things can happen.
Could you please provide the error log (administration -> information -> logging)?
And are you testing with Humhub 1.14-beta ?
Maybe the PHP version is also interesting.

And please try to save the Flex Theme settings (again). Maybe that helps for the moment.

**Comment by felixhahnweilheim** [comment] 2023-04-08 22:19
I close the issue because I can't reproduce the error. If it still occurs please re-open the issue and give more details.

**Closed by felixhahnweilheim** 2023-04-08 22:19 UTC
Labels: Unable to reproduce
